### ISSUE TITLE
Print traj fails for dataframe with one frame

### ISSUE THREAD

**Issue by MaikFZJ** [PedestrianDynamics/PedPy#223]
Following code raises an error:

traj = pedpy.load_trajectory(...)
frame_100 = traj.data.groupby("frame").get_group(100)
traj = pedpy.TrajectoryData(data=frame_100, frame_rate=traj.frame_rate)
print(traj)

Coming from "bounding box: {shapely.MultiPoint(self.data.point).bounds}"

**Comment by Ozaq** [comment]
See the issue, will add a fix.

**Comment by Ozaq** [comment]
@MaikFZJ After looking into the issue: 

So what happens here is that you select a `pandas.Series` from the `pandas.DataFrame` and create a new `TrajectoryData` with the wrong types as input.

Concrete:
```python
traj = pedpy.load_trajectory(...)
# frame_100 is of type pandas.Series
frame_100 = traj.data.groupby("frame").get_group(100)
# here we expect data to be a `pandas.DataFrame` 
traj = pedpy.TrajectoryData(data=frame_100, frame_rate=traj.frame_rate)
# this is the first time we use something on data that is not supported by `pandas.Series` hence you see the exception
print(traj)
```

In python you generally get exceptions if you call code with the wrong data types so the behaviour you see is the expected behaviour in Python, further we provide type hints on those methods. Your IDE should show you an error if you use pyright or mypy for example.

I am hesitant to change the current behaviour as it is well within what is expected in Python.
